name: WakaTime Readme Stats 🕒

on:
  schedule:
    # Update setiap hari jam 00:00 UTC
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: "true"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_COMMIT: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_LINES_OF_CODE: "true"
          COMMIT_MESSAGE: "✨ Update wakatime stats"
          LOCALE: "en"
