name: Update WakaTime Box

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-box:
    runs-on: ubuntu-latest
    steps:
      - uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
