name: Waka Readme Stats

on:
  schedule:
    - cron: "0 0 * * *" # update setiap hari
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_EDITORS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LOC_CHART: "False"
